export const TOGGLE_MENU = "TOGGLE_MENU";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING = "LOADING";

export const SET_USER = "SET_USER";
export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const GET_USER = "GET_USER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_ADMIN_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_PRODUCT_TYPES = "GET_PRODUCT_TYPES";
export const GET_ADMIN_PRODUCT_TYPES = "GET_PRODUCT_TYPES";
export const DELETE_PRODUCT_TYPE = "DELETE_PRODUCT_TYPE";

export const GET_PRODUCT_CATEGORIES = "GET_PRODUCT_CATEGORIES";
export const GET_ADMIN_PRODUCT_CATEGORIES = "GET_PRODUCT_CATEGORIES";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
